import type { FieldSchema, FieldType } from '../types';

// Available field types for the generator
export const fieldTypes: FieldType[] = [
  { value: 'string', label: 'String' },
  { value: 'number', label: 'Number' },
  { value: 'boolean', label: 'Boolean' },
  { value: 'object', label: 'Object' },
  { value: 'array', label: 'Array' },
  { value: 'uuid', label: 'UUID' },
  { value: 'fullName', label: 'Full Name' },
  { value: 'firstName', label: 'First Name' },
  { value: 'lastName', label: 'Last Name' },
  { value: 'email', label: 'Email' },
  { value: 'phone', label: 'Phone' },
  { value: 'date', label: 'Date' },
  { value: 'dateTime', label: 'Date & Time' },
  { value: 'address', label: 'Address' },
  { value: 'city', label: 'City' },
  { value: 'country', label: 'Country' },
  { value: 'zipCode', label: 'Zip Code' },
  { value: 'gender', label: 'Gender' },
  { value: 'sex', label: 'Sex' },
  { value: 'username', label: 'Username' },
  { value: 'password', label: 'Password' },
  { value: 'avatar', label: 'Avatar URL' },
  { value: 'color', label: 'Color' },
  { value: 'url', label: 'URL' },
  { value: 'ipAddress', label: 'IP Address' },
  { value: 'creditCard', label: 'Credit Card' },
  { value: 'paragraph', label: 'Paragraph' },
  { value: 'jobTitle', label: 'Job Title' },
  { value: 'company', label: 'Company' },
  { value: 'currency', label: 'Currency Amount' },
];

// Field descriptions for UI tooltips and help text
export const fieldDescriptions: Record<string, string> = {
  object: 'Nested object containing multiple fields',
  array: 'Array of items',
  string: 'Random string of characters',
  number: 'Random number within specified range',
  boolean: 'Random true/false value',
  uuid: 'Random UUID (universally unique identifier)',
  fullName: 'Random full name (first and last)',
  firstName: 'Random first name',
  lastName: 'Random last name',
  email: 'Random email address',
  phone: 'Random phone number',
  date: 'Random date in YYYY-MM-DD format',
  dateTime: 'Random date and time in ISO format',
  gender: 'Random gender category',
  sex: 'Random biological sex category',
  address: 'Random street address',
  city: 'Random city name',
  country: 'Random country name',
  zipCode: 'Random zip/postal code',
  username: 'Random username',
  password: 'Random secure password',
  avatar: 'Random avatar URL',
  color: 'Random hex color code',
  url: 'Random website URL',
  ipAddress: 'Random IP address',
  creditCard: 'Random credit card number format',
  paragraph: 'Random paragraph of text',
  jobTitle: 'Random job title',
  company: 'Random company name',
  currency: 'Random currency amount',
};

// Default schema to initialize the generator
export const defaultSchema: FieldSchema[] = [
  { name: 'id', type: 'uuid', required: true },
  { name: 'name', type: 'fullName', required: true },
  { name: 'email', type: 'email', required: true },
  {
    name: 'address',
    type: 'object',
    required: true,
    fields: [
      { name: 'street', type: 'address', required: true },
      { name: 'city', type: 'city', required: true },
      { name: 'zipCode', type: 'zipCode', required: true },
      { name: 'country', type: 'country', required: true },
    ],
  },
];
