export const COUNTRIES = [
  ['United States', 'US'],
  ['United Kingdom', 'GB'],
  ['Germany', 'DE'],
  ['France', 'FR'],
  ['Spain', 'ES'],
  ['Ireland', 'IE'],
  ['Canada', 'CA'],
  ['Australia', 'AU'],
  ['Japan', 'JP'],
  ['Brazil', 'BR'],
  ['India', 'IN'],
  ['China', 'CN'],
  ['Mexico', 'MX'],
  ['South Africa', 'ZA'],
  ['Italy', 'IT'],
  ['Netherlands', 'NL'],
  ['Sweden', 'SE'],
  ['Norway', 'NO'],
  ['Poland', 'PL'],
  ['Portugal', 'PT'],
  ['New Zealand', 'NZ'],
  ['Singapore', 'SG'],
  ['South Korea', 'KR'],
  ['Argentina', 'AR'],
  ['Nigeria', 'NG'],
  ['Egypt', 'EG'],
  ['Kenya', 'KE'],
  ['Turkey', 'TR'],
  ['Greece', 'GR'],
  ['Switzerland', 'CH'],
] as const;
