import {
  IconBattery,
  IconDroplet,
  IconGauge,
  IconHardDrive,
  IconRuler,
  IconScale,
  IconSquare,
  IconThermometer,
  IconTimer,
  IconZap,
} from '@/shared/ui/icons';

import type { Category } from '../types';

/** Every category with its units; `factor` converts a unit to `baseUnit`. */
export const CATEGORIES: Category[] = [
  {
    name: 'Length',
    icon: <IconRuler size="md" />,
    baseUnit: 'meters',
    units: [
      { name: 'Kilometers', symbol: 'km', factor: 1000 },
      { name: 'Meters', symbol: 'm', factor: 1 },
      { name: 'Centimeters', symbol: 'cm', factor: 0.01 },
      { name: 'Millimeters', symbol: 'mm', factor: 0.001 },
      { name: 'Miles', symbol: 'mi', factor: 1609.34 },
      { name: 'Yards', symbol: 'yd', factor: 0.9144 },
      { name: 'Feet', symbol: 'ft', factor: 0.3048 },
      { name: 'Inches', symbol: 'in', factor: 0.0254 },
    ],
  },
  {
    name: 'Weight',
    icon: <IconScale size="md" />,
    baseUnit: 'grams',
    units: [
      { name: 'Tonnes', symbol: 't', factor: 1000000 },
      { name: 'Kilograms', symbol: 'kg', factor: 1000 },
      { name: 'Grams', symbol: 'g', factor: 1 },
      { name: 'Milligrams', symbol: 'mg', factor: 0.001 },
      { name: 'Pounds', symbol: 'lb', factor: 453.592 },
      { name: 'Ounces', symbol: 'oz', factor: 28.3495 },
    ],
  },
  {
    name: 'Volume',
    icon: <IconDroplet size="md" />,
    baseUnit: 'liters',
    units: [
      { name: 'Cubic Meters', symbol: 'm³', factor: 1000 },
      { name: 'Liters', symbol: 'L', factor: 1 },
      { name: 'Milliliters', symbol: 'mL', factor: 0.001 },
      { name: 'Gallons (US)', symbol: 'gal', factor: 3.78541 },
      { name: 'Quarts', symbol: 'qt', factor: 0.946353 },
      { name: 'Pints', symbol: 'pt', factor: 0.473176 },
      { name: 'Cups', symbol: 'cup', factor: 0.236588 },
      { name: 'Fluid Ounces', symbol: 'fl oz', factor: 0.0295735 },
    ],
  },
  {
    name: 'Temperature',
    icon: <IconThermometer size="md" />,
    baseUnit: 'kelvin',
    units: [
      { name: 'Kelvin', symbol: 'K', factor: 1 },
      { name: 'Celsius', symbol: '°C', factor: 1, offset: 273.15 },
      { name: 'Fahrenheit', symbol: '°F', factor: 5 / 9, offset: 459.67 },
    ],
  },
  {
    name: 'Area',
    icon: <IconSquare size="md" />,
    baseUnit: 'square meters',
    units: [
      { name: 'Square Kilometers', symbol: 'km²', factor: 1000000 },
      { name: 'Hectares', symbol: 'ha', factor: 10000 },
      { name: 'Square Meters', symbol: 'm²', factor: 1 },
      { name: 'Square Miles', symbol: 'mi²', factor: 2589988.11 },
      { name: 'Acres', symbol: 'ac', factor: 4046.86 },
      { name: 'Square Feet', symbol: 'ft²', factor: 0.092903 },
      { name: 'Square Inches', symbol: 'in²', factor: 0.00064516 },
    ],
  },
  {
    name: 'Speed',
    icon: <IconZap size="md" />,
    baseUnit: 'meters per second',
    units: [
      { name: 'Meters per Second', symbol: 'm/s', factor: 1 },
      { name: 'Kilometers per Hour', symbol: 'km/h', factor: 0.277778 },
      { name: 'Miles per Hour', symbol: 'mph', factor: 0.44704 },
      { name: 'Knots', symbol: 'kn', factor: 0.514444 },
      { name: 'Feet per Second', symbol: 'ft/s', factor: 0.3048 },
    ],
  },
  {
    name: 'Time',
    icon: <IconTimer size="md" />,
    baseUnit: 'seconds',
    units: [
      { name: 'Years', symbol: 'yr', factor: 31536000 },
      { name: 'Months', symbol: 'mo', factor: 2628000 },
      { name: 'Weeks', symbol: 'wk', factor: 604800 },
      { name: 'Days', symbol: 'd', factor: 86400 },
      { name: 'Hours', symbol: 'h', factor: 3600 },
      { name: 'Minutes', symbol: 'min', factor: 60 },
      { name: 'Seconds', symbol: 's', factor: 1 },
      { name: 'Milliseconds', symbol: 'ms', factor: 0.001 },
    ],
  },
  {
    name: 'Data',
    icon: <IconHardDrive size="md" />,
    baseUnit: 'bytes',
    units: [
      { name: 'Terabytes', symbol: 'TB', factor: 1099511627776 },
      { name: 'Gigabytes', symbol: 'GB', factor: 1073741824 },
      { name: 'Megabytes', symbol: 'MB', factor: 1048576 },
      { name: 'Kilobytes', symbol: 'KB', factor: 1024 },
      { name: 'Bytes', symbol: 'B', factor: 1 },
      { name: 'Bits', symbol: 'bit', factor: 0.125 },
    ],
  },
  {
    name: 'Pressure',
    icon: <IconGauge size="md" />,
    baseUnit: 'pascals',
    units: [
      { name: 'Gigapascals', symbol: 'GPa', factor: 1000000000 },
      { name: 'Megapascals', symbol: 'MPa', factor: 1000000 },
      { name: 'Kilopascals', symbol: 'kPa', factor: 1000 },
      { name: 'Pascals', symbol: 'Pa', factor: 1 },
      { name: 'Bars', symbol: 'bar', factor: 100000 },
      { name: 'Atmospheres', symbol: 'atm', factor: 101325 },
      { name: 'Pounds per Square Inch', symbol: 'psi', factor: 6894.76 },
    ],
  },
  {
    name: 'Energy',
    icon: <IconBattery size="md" />,
    baseUnit: 'joules',
    units: [
      { name: 'Kilojoules', symbol: 'kJ', factor: 1000 },
      { name: 'Joules', symbol: 'J', factor: 1 },
      { name: 'Calories', symbol: 'cal', factor: 4.184 },
      { name: 'Kilocalories', symbol: 'kcal', factor: 4184 },
      { name: 'Watt-hours', symbol: 'Wh', factor: 3600 },
      { name: 'Kilowatt-hours', symbol: 'kWh', factor: 3600000 },
      { name: 'Electron-volts', symbol: 'eV', factor: 1.602177e-19 },
      { name: 'British Thermal Units', symbol: 'BTU', factor: 1055.06 },
    ],
  },
];
