/**
 * Converts the `~/tools` wordmark into SVG outlines (JetBrains Mono, OFL) so
 * the Logo component draws paths, never text (spec §4.3).
 * Run through `pnpm icons:gen`; the output is committed.
 *
 * @pdf-lib/fontkit cannot instance a variable WOFF2 (getVariation loses the
 * cmap), so the outlines use the font's default instance (wght 400).
 */
import { readFile, writeFile } from 'node:fs/promises';
import fontkit from '@pdf-lib/fontkit';

const FONT =
  'node_modules/@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-wght-normal.woff2';
const OUT = 'src/shared/ui/icons/brand/logo-paths.ts';
const TEXT = '~/tools';
const SIZE = 24; // em size in viewBox units

const round = (n: number) => Math.round(n * 100) / 100;

/**
 * fontkit emits absolute M/L/Q/C/Z commands in font units (y up). Scale,
 * flip y about the baseline and offset x.
 */
function transformPath(
  d: string,
  scale: number,
  dx: number,
  baseline: number,
): string {
  return d.replace(/([MLQCZ])([^MLQCZ]*)/g, (_, cmd: string, args: string) => {
    const nums = args.trim()
      ? args
          .trim()
          .split(/[\s,]+/)
          .map(Number)
      : [];
    const out: number[] = [];
    for (let i = 0; i < nums.length; i += 2) {
      out.push(
        round(nums[i] * scale + dx),
        round(baseline - nums[i + 1] * scale),
      );
    }
    return cmd + out.join(' ');
  });
}

const font = fontkit.create(new Uint8Array(await readFile(FONT)));
const run = font.layout(TEXT);
const s = SIZE / font.unitsPerEm;
const baseline = font.ascent * s;
let x = 0;
const paths: string[] = [];
run.glyphs.forEach((g, i) => {
  paths.push(transformPath(g.path.toSVG(), s, x, baseline));
  x += run.positions[i].xAdvance * s;
});
const width = Math.ceil(x);
const height = Math.ceil((font.ascent - font.descent) * s);
const caret = {
  x: width + 2,
  y: Math.round(baseline * 0.22),
  width: Math.round(SIZE * 0.42),
  height: Math.round(baseline * 0.8),
};
await writeFile(
  OUT,
  `// Generated by scripts/gen-logo.ts from JetBrains Mono (OFL). Do not edit.
export const LOGO_GLYPHS =
  '${paths.join('')}';
export const LOGO_WIDTH = ${width};
export const LOGO_HEIGHT = ${height};
export const CARET = ${JSON.stringify(caret).replace(/"/g, '')};
`,
);
