export const TOOL_IDS = {
  COLOR_TESTER: "color-tester",
  PASSWORD_GENERATOR: "password-generator",
  REGEX_TESTER: "regex-tester",
  NUMBER_CONVERTER: "number-converter",
  QR_CODE_GENERATOR: "qr-code-generator",
  JSON_AND_XML_VIEWER: "json-and-xml-viewer",
  POMODORO: "pomodoro",
  UNIT_CONVERTER: "unit-converter",
  PERIODIC_TABLE: "periodic-table",
  TEXT_DIFF_CHECKER: "text-diff-checker",
  MARKDOWN_EDITOR: "markdown-editor",
  IMAGE_OPTIMIZER: "image-optimizer",
  CSV_VIEWER: "csv-viewer",
  CODE_FORMATTER: "code-formatter",
  RANDOM_DATA_GENERATOR: "random-data-generator",
  URL_ENCODER: "url-encoder-decoder",
  DATE_CALCULATOR: "date-calculator",
  HASH_GENERATOR: "hash-generator",
  NOTE_TAKING: "note-taking",
  BASE64_CONVERTER: "base64-converter",
  JWT_DECODE: "jwt-decode",
  URL_PARSER: "url-parser",
  API_REQUEST: "api-request",
  CALCULATOR: "calculator",
} as const;