export const TOOL_IDS = {
  COLOR_TESTER: 'color-tester',
  PASSWORD_GENERATOR: 'password-generator',
  REGEX_TESTER: 'regex-tester',
  NUMBER_CONVERTER: 'number-converter',
  QR_CODE_GENERATOR: 'qr-code-generator',
  JSON_AND_XML_VIEWER: 'json-and-xml-viewer',
  POMODORO: 'pomodoro',
  UNIT_CONVERTER: 'unit-converter',
  TEXT_DIFF_CHECKER: 'text-diff-checker',
  IMAGE_OPTIMIZER: 'image-optimizer',
  CSV_VIEWER: 'csv-viewer',
  RANDOM_DATA_GENERATOR: 'random-data-generator',
  URL_ENCODER: 'url-encoder-decoder',
  DATE_CALCULATOR: 'date-calculator',
  HASH_GENERATOR: 'hash-generator',
  BASE64_CONVERTER: 'base64-converter',
  JWT_DECODE: 'jwt-decode',
  URL_PARSER: 'url-parser',
  API_REQUEST: 'api-request',
  CALCULATOR: 'calculator',
  LOG_PARSER: 'log-parser',
  RIVE_ANIMATION_PLAYER: 'rive-animation-player',
  PDF_MERGER: 'pdf-merger',
  PDF_SPLITTER: 'pdf-splitter',
  PDF_COMPRESSOR: 'pdf-compressor',
} as const;
