name: Build & publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write

concurrency:
  group: publish-build
  cancel-in-progress: false

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: CI=true pnpm install --frozen-lockfile

      - name: Build
        env:
          CI: true
        run: pnpm build

      - name: Push build to branch
        if: github.event_name == 'push'
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Build: ({sha}) {msg}'
          SKIP_EMPTY_COMMITS: 'true'
          CLEAR_GLOBS_FILE: '.clear-target-files'
